stages:
    weekly_summary:
        cmd: julia --project=@. scripts/weekly_summary.jl "Weekly"
        deps:
            - scripts/weekly_summary.jl
        outs:
            - data/net_transfer_by_item.csv
            - data/net_expense.csv
            - data/expense_book.csv
            - data/transfer_book.csv
