# You have to set PAT and add secrete ACCESS_OKREGISTRY in the repo {{{PKG}}}
# https://stevenmortimer.com/running-github-actions-sequentially/
# see also the default template: https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/register.yml

name: SendMailYearly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 1 1 *" # Run every year ()
    # The first 0 represents the minute (0 to 59).
    # The second represents the hour (0 to 23).
    # The third 1 represents the day of the month (1 to 31).
    # The fourth 1 represents the month (1 to 12).
    # The * in the fifth position represents any day of the week.
jobs:
  send:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: okatsn/add-registry@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=@. -e 'include("scripts/weekly_summary.jl")' "${{ secrets.GMAIL_APP_ADDRESS }}" "${{ secrets.GMAIL_APP_KEY }}" "${{ secrets.GSHEET_KEY }}" "Yearly"
